
CLASS ma.cls.basemaauthautodetail INHERITS cls.mip:

/*
 This program is no longer in use.
 New program name basemaauthgroupdetail.cls
*/
  /* -- CONSTRUCTOR -------------------------------------------------- */
  CONSTRUCTOR PUBLIC basemaauthautodetail() :
  /*------------------------------------------------------------------
      Purpose: Empty constructor   
        Notes:
  -------------------------------------------------------------------- */
    
    SUPER().
    
    { mip/inc/mipcatcherror.i }
    
  END CONSTRUCTOR. /* CONSTRUCTOR PUBLIC basemaauthautodetail */

END CLASS.  /* mip.cls.basemaauthautodetail */
