/*------------------------------------------------------------------------
    Component: Healthcare SOA
       Author: Andrewd

      Purpose: Base Authorisation Repeat Class
------------------------------------------------------------------------*/
CLASS ma.cls.basemaauthorisationrepeat INHERITS cls.mip:

/* Class is no longer needed due to the DB table for tt_auth_repeat being removed */

END CLASS.  /* mip.cls.basemaauthorisationrepeat */
