CLASS ma.cls.basemaauthautogroup INHERITS cls.mip:
/* 
 This progrma is no longer in use.*/
  /* -- CONSTRUCTOR -------------------------------------------------- */
  CONSTRUCTOR PUBLIC basemaauthautogroup():
  /*------------------------------------------------------------------
      Purpose:  
        Notes:  
  -------------------------------------------------------------------- */
    SUPER().
  END CONSTRUCTOR. /* CONSTRUCTOR PUBLIC basemaauthautogroup */

END CLASS.  /* mip.cls.basemaAuthAutoGroup */
