CLASS ma.cls.basemaauthautogroupsearch :
/*
 This program is no longer in use.
 New program name basemaauthgroupsearch.cls
 
*/
 { ma/inc/maauthautods.i }
   /* -- CONSTRUCTOR ---------------------------------------------------------- */
  CONSTRUCTOR PUBLIC basemaauthautogroupsearch
    ():
  /*-----------------------------------------------------------------------------
      Purpose:
  -----------------------------------------------------------------------------*/
 
 
  END CONSTRUCTOR. /* CONSTRUCTOR PUBLIC basemaauthautogroupsearch */
END CLASS. /* CLASS ma.cls.basemaauthautogroupsearch INHERITS cls.mipdataretrieval */
