
/*Program no longer in use 
New program name maauthgroup.cls*/
CLASS cls.maauthautogroup INHERITS ma.cls.basemaauthautogroup:
  /* -- CONSTRUCTOR -------------------------------------------------- */
  CONSTRUCTOR PUBLIC maauthautogroup() :
  /*------------------------------------------------------------------
      Purpose: Empty constructor   
        Notes:
  -------------------------------------------------------------------- */
    
    SUPER().
  END CONSTRUCTOR. /* CONSTRUCTOR PUBLIC basemaAuthAutoGroup */  

END CLASS. /* cls.maauthautogroup INHERITS ma.cls.basemaauthautogroup */


