/*program no longer in use 
New Program name maauthgroupdetail.cls*/
CLASS cls.maauthautoDetail INHERITS ma.cls.basemaauthautodetail:
  /* -- CONSTRUCTOR -------------------------------------------------- */
  CONSTRUCTOR PUBLIC maauthautodetail() :
  /*------------------------------------------------------------------
      Purpose: Empty constructor   
        Notes:
  -------------------------------------------------------------------- */
    
    SUPER().
  END CONSTRUCTOR. /* CONSTRUCTOR PUBLIC basemaAuthAutoDetail */  
END CLASS. /* cls.maauthautoDetail INHERITS ma.cls.basemaauthautoDetail */

