/*program no longer in use 
New Program name maauthgroupsearch.cls*/
CLASS cls.maauthautogroupsearch INHERITS ma.cls.basemaauthautogroupsearch:

  CONSTRUCTOR PUBLIC maauthautogroupsearch
    ():
  /*-----------------------------------------------------------------------------
      Purpose:
  -----------------------------------------------------------------------------*/
   

  END CONSTRUCTOR. /* CONSTRUCTOR PUBLIC maauthautogroupsearch */
END CLASS. /* CLASS cls.maauthautogroupsearch INHERITS ma.cls.basemaauthautogroupsearch */
