/* -----------------------------------------------------------------------------
  This is a wrapper to provide easy configuration of Class over-rides.
----------------------------------------------------------------------------- */
CLASS cls.maauthorisationrepeat INHERITS ma.cls.basemaauthorisationrepeat:

/* Class is no longer needed as the hat_auth_repat and hah_auth_repeat_history has been removed */

END CLASS. /* cls.maauthorisationrepeat INHERITS ma.cls.basemaauthorisationrepeat */

